### ISSUE TITLE
Multi variable subscribe

### ISSUE THREAD

**Issue by methaqali** [ubidots/ubidots-nodered#11]
Hey, 
I use plc LSIS-type connected to opc server which send data to node-red successfully. also I add MQTT nodes publish and l subscribe with opc server on local host to send the data to ubidots. I had use ubidots nodes for publish and subscribe as a primary test, the problem is in subscribing I can't listen to more than one variable.
How can I solve this problem?

**Comment by d4vsanchez** [comment]
I think I have found what's causing this behavior. 

The following block (https://github.com/ubidots/ubidots-nodered/blob/85985078baacca3de60a504217db83c6f704dd3c/ubidots/ubidots_in.js#L7-L9) is ending the previous connection of the client and this could cause the other connections to the variables to stop listening.
