### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by Sordnay** [ubidots/ubidots-nodered#16]
**Describe the bug**
I use two ubidots_out nodes to send information to be logged on ubidots,  found them with the same error, and there was no way to make it to re-connect. everything else was ok, msg coming to the node ok, etc.

Finally fixing it inserting a new node with the same configuration, and started publishing without problem.

After looking breafly at the code, I barely understand js, I had an idea: on connect after publishing, there is a client.end(true) I'm guessing there should be another one after the  "on error"?

**To Reproduce**
I've been unable to reproduce, I think it was an error on ubidots side. Installed a logger, maybe next time i have more info. restarting flow did not fix the problem.

**Expected behavior**
I would like the node to issue an error (another node output port?) an be ready for the next communication as soon as possible. 

**Screenshots**
just ubidots-out on error state.

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [Versión 70.0.3538.102 (Build oficial) (64 bits)]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jotathebest** [comment]
solved at #25
